### ISSUE TITLE
Instead of asking people to sign letters on Google Forms, open bug reports and ask people to duplicate these report

### ISSUE THREAD

**Issue by LeoNatan** [dear-apple/dear-apple#1]
Apple works with their bug reporting system; instead of encouraging people to sign letters (on Google Forms no less) - open a bug report at https://bugreport.apple.com, post the bug number and encourage people to duplicate it. This is the only way to move something at Apple.

**Comment by kevinbarabash** [comment]
Does Apple even look at bug reports?  I've filed reports in the past and never heard anything back.

**Comment by LeoNatan** [comment]
Yes they do. The way it works is, the more people report the same issue, the more chances there are for something to change.

**Comment by MikhailTNY** [comment]
Apple has responded to almost half of my reports, so they do look and review them but like every other big company, they will not reply to each one individually because they'd be spending all the time replying to reports only. They do prioritize based on dupes, as confirmed by some Apple engineers.  

They do need a better bug reporter system for sure. For now, definitely file these reports or dupe an existing one.

**Comment by pepibumur** [comment]
I'll definitively fill radars for those that are bugs and encourage people there to do is as well. I'll update the request accordingly. 

For things that are not bugs but are requests for the IDE couldn't find any channel.

**Comment by LeoNatan** [comment]
@pepibumur For enhancement requests, use "Enhancement Request" as the bug type.

**Comment by pepibumur** [comment]
Thanks @LeoNatan I'll update the REDME accordingly. Thanks 👍
